# Generated by Django 3.2.3 on 2021-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210601_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='texto',
            field=models.TextField(max_length=1000, verbose_name='Descrição'),
        ),
    ]
